### ISSUE TITLE
Can't use same variable name for export and import

### ISSUE THREAD

**Issue by webdesserts** [esperantojs/esperanto#146]
If I use the same export name twice like so:

```js
// src/myModule.js
var myModule = {}
export default myModule
```

```js
// index.js
import myModule from './src/myModule.js';
// do stuff with myModule
export default myModule
```

I get the following error:

```bash
Error: Cannot replace the same content twice
    at Object.MagicString.replace (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/magic-string/dist/magic-string.js:668:11)
    at /Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:1334:11
    at Array.forEach (native)
    at combine_transformBody__transformBody (/Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:1309:14)
    at /Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:1440:13
    at Array.forEach (native)
    at combine (/Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:1422:17)
    at /Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:1548:4
    at $$$internal$$tryCatch (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:304:16)
    at $$$internal$$invokeCallback (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:316:17)
    at $$$internal$$publish (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:287:11)
    at $$asap$$flush (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:111:9)
    at process._tickDomainCallback (node.js:381:11)
```

This is pretty common for me when writing node modules

**Comment by eventualbuddha** [comment]
It's a combination of two things: 1) forcing esperanto to rename the `myModule` variable and 2) re-exporting the default import. This also reproduces this exception:

```js
// src/myModule.js
var myModule = {}
export default myModule

// index.js
import foo from './src/myModule.js';
// do stuff with myModule
export default foo;
var myModule;
```

Using this command: `esperanto -i index.js -b`.

**Comment by webdesserts** [comment]
And just to expand on this, I originally expected the output to be the two files concatenated together with only the final export. For example if this was a cjs bundle I was expecting something like:

```js
var myModule = {}
// do stuff with myModule
module.exports = myModule
```
