### ISSUE TITLE
Can't generate inline sourcemaps

### ISSUE THREAD

**Issue by webdesserts** [esperantojs/esperanto#147]
On 0.6.27 I can't seem to get inline sourcemaps working with a bundle. I keep getting the following error:

```
TypeError: Cannot read property 'split' of null
    at Object.Bundle.generateMap (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/magic-string/dist/magic-string.js:120:23)
    at packageResult (/Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:1756:14)
    at builders_defaultsMode_cjs__cjs (/Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:2326:9)
    at transpile (/Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:2578:12)
    at Object.toCjs (/Users/michael/code/alchemist-js/node_modules/esperanto/dist/esperanto.js:2544:39)
    at /Users/michael/code/alchemist-js/gulpfile.js:63:33
    at $$$internal$$tryCatch (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:304:16)
    at $$$internal$$invokeCallback (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:316:17)
    at $$$internal$$publish (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:287:11)
    at $$asap$$flush (/Users/michael/code/alchemist-js/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:111:9)
    at process._tickDomainCallback (node.js:381:11)
```

I believe the lines referenced in the error are [here](https://github.com/Rich-Harris/magic-string/blob/master/src/Bundle/index.js#L60) and [here](https://github.com/esperantojs/esperanto/blob/master/src/utils/packageResult.js#L26-L27)

The relevant parts of my code look like this:
```js
    //...
    return esperanto.bundle({ entry: file })
    .then(function (bundle) {
      return bundle[format_func]({
        sourceMap: 'inline',
        sourceMapFile: file + '.map'
      });
    })
   //...
```

**Comment by Rich-Harris** [comment]
Thanks @webdesserts, this has been fixed upstream. If you reinstall esperanto (which will get the latest version of its dependency magic-string) it should work now

**Comment by webdesserts** [comment]
@Rich-Harris Looks like everything is working on my end. Thanks for the fix :)
