### ISSUE TITLE
Error when using CLI to bundle with inline sourcemaps and no output

### ISSUE THREAD

**Issue by patrickarlt** [esperantojs/esperanto#179]
**Command**

```js
esperanto -i ./src/EsriLeaflet.js --skip=leaflet -t umd --strict --name L.esri --bundle -m inline
```

**Error**

```js
Arguments to path.resolve must be strings
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:422:13)
    at /Users/patricklocal/.nvm/versions/v0.12.1/lib/node_modules/esperanto/bin/runEsperanto.js:69:60
    at lib$es6$promise$$internal$$tryCatch (/Users/patricklocal/.nvm/versions/v0.12.1/lib/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/Users/patricklocal/.nvm/versions/v0.12.1/lib/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (/Users/patricklocal/.nvm/versions/v0.12.1/lib/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (/Users/patricklocal/.nvm/versions/v0.12.1/lib/node_modules/esperanto/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at process._tickCallback (node.js:355:11)
```

I think there needs to be a special case for handling inline source maps here https://github.com/esperantojs/esperanto/blob/master/bin/runEsperanto.js#L69.

I mainly would like this so I can pipe the file (with inline sourcemap) to exorcist and solve https://github.com/esperantojs/esperanto/issues/178

**Comment by Rich-Harris** [comment]
@patrickarlt sorry for the slow response. I just cloned esri-leaflet so I could send you a PR replacing Esperanto with Rollup but it looks like you're way ahead of me! Is this still an issue with Rollup, or is it fixed? If it's not fixed, any chance you could raise an issue over [there](https://github.com/rollup/rollup/issues) please? Am afraid this is a wontfix as far as Esperanto is concerned, as I'm winding it down (#191).
